// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbpxoxkyuihtndlncmdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpicHhveGt5dWlodG5kbG5jbWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDQ1OTgsImV4cCI6MjA3MDY4MDU5OH0.K6M1t3r_mfmI6_FtWhX0bp2K7CohQhsPNz50F1AuQHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});